import random

from generators.generator import Generator
from maze import Maze
from type_of_cell import TypeOfCell


class BinaryTreeGenerator(Generator):
    """
    Class for maze generator based on the BinaryTree algorithm
    """

    def __init__(self, height: int, width: int) -> None:
        """Initialize the BinaryTreeGenerator with the specified height and width"""
        super().__init__(height, width)

    def generate(self) -> Maze:
        """Generate a maze using the BinaryTree algorithm"""
        self._create_random_grid()
        self._preprocess_grid()

        final_grid: list[list[str]] = self._get_carved_maze()
        generated_maze: Maze = Maze(self._height, self._width, final_grid)

        return generated_maze

    def _create_random_grid(self) -> None:
        """Create a random binary grid"""
        random_grid: list[list[int]] = [
            [random.randint(0, 1) for _ in range(self._width)]
            for _ in range(self._height)
        ]

        self._grid: list[list[int]] = random_grid

    def _preprocess_grid(self) -> None:
        """Preprocess the grid before carving the maze"""
        first_row: list[int] = self._grid[0]
        first_row = [0 if cell == 1 else cell for cell in first_row]
        self._grid[0] = first_row

        for i in range(1, self._height):
            self._grid[i][self._width - 1] = 1

    def _get_carved_maze(self) -> list[list[str]]:
        """Carve the maze based on the grid generated by the algorithm"""
        final_grid: list[list[str]] = [
            [TypeOfCell.WALL.value for _ in range(self._width * 2 + 1)]
            for _ in range(self._height * 2 + 1)
        ]

        for i in range(self._height):
            for j in range(self._width):
                w: int = i * 2 + 1
                k: int = j * 2 + 1
                toss: int = self._grid[i][j]
                final_grid[w][k] = TypeOfCell.EMPTY.value
                if toss == 0 and k + 2 < self._width * 2:
                    final_grid[w][k + 1] = TypeOfCell.EMPTY.value
                    final_grid[w][k + 2] = TypeOfCell.EMPTY.value
                elif toss == 1 and w - 2 >= 0:
                    final_grid[w - 1][k] = TypeOfCell.EMPTY.value
                    final_grid[w - 2][k] = TypeOfCell.EMPTY.value

        return final_grid
